### ISSUE TITLE
Can`t use this with Composer 2.0.x

### ISSUE THREAD

**Issue by raphacmartin** [kylekatarnls/update-helper#11]
Now Composer 2 version is stable, so when I do 

`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`
`php composer-setup.php`
`php composer.phar --version`

In a project that uses Carbon (I`m working on a laravel/lumen 5.7 project that uses Carbon 1), I receive

> PHP Fatal error:  Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /path/to/my/project/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11
> 
> Fatal error: Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /path/to/my/project/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11

For me, a workaround is install the latest 1 version of composer
`php composer-setup.php --version=1.10.16`

Any chance to solve this?

**Comment by kylekatarnls** [comment]
Support of Composer 2 <s>is in progress</s> has been provided in 1.2.1. Note that you get `update-helper` installed because you have a deprecated package in your stack (Lumen 5.7 is now very old). As you seem to appreciate being up to date with Composer, please consider being so with Lumen.

**Comment by kylekatarnls** [comment]
Hello, I just checked with a fresh install of Composer 2.0.3 and ran `./composer.phar require nesbot/carbon:^1`, this installed it smoothly. So my guess is that you have an old version of update-helper (< 1.2.1), so you should first updatre (with `--no-scripts` flag), then running other install/update after that should work normally.

We can't provide any fix for that as obviously we can't change the code of a version already released and installed on your machine.

Mostly the root cause is it has been previously installed with Composer 1 (or composer.lock was generated with Composer 1) and you upgrade to Composer 2 before updating the project dependencies/composer.lock.

If you think it's a different problem, please provide a complete list of commands I can execute to reproduce the bug and I'll re-open.

Thanks.

**Comment by simonhamp** [comment]
`--no-scripts` didn't work for me, I had to use `--no-plugins`
