### ISSUE TITLE
Upgrading laravel 5.7 to 5.8

### ISSUE THREAD

**Issue by dennysutanto** [kylekatarnls/update-helper#13]
Hi, i want to upgrade laravel from 5.7 to 5.8
Step to produce the error

1. changed "laravel/framework": "5.7.*", to "laravel/framework": "5.8.*" in composer.json, 
2. then i run composer update
3. i see this error, but seems like the process is completed

The "kylekatarnls/update-helper" plugin was skipped because it requires a Plugin API version ("^1.1.0") that does not match your Composer installation ("2.0.0"). 
You may need to run composer update with the "--no-plugins" option.

What should i do to fix the above ? Thanks

**Comment by kylekatarnls** [comment]
Yes, composer 2 was released after the version of update-helper you have installed in your vendor, then you upgraded composer meanwhile. So there is no way to fix it from our side, it will fail the first time then should be good on next update since update-helper will be updated to a version that supports composer 2.

For the record, the actual way to avoid this would have been first update your project with composer 1 (so every patches are installed), then install composer 2, re-update your project, and finally do your migration for major/minor version of the framework.

Note that 5.8 is still very obsolete, and regarding the big step ahead, it might be worth it to continue the upgrade up to 8 in the same move.

**Comment by dennysutanto** [comment]
thanks for your prompt reply @kylekatarnls .
Noted on the above, yes, i plan to continue upgrading to laravel 8
